### ISSUE TITLE
Build for petalinux v2020.2

### ISSUE THREAD

**Issue by thangta** [ikwzm/zynqmp-gpu-kmod-dpkg#2]
hi, 
Could you support build for petalinux v2020.2 

Many thank for that

**Comment by ikwzm** [comment]
Thank you for the issue.

I'm not using Petalinux.
What kind of support do you need specifically?

**Comment by thangta** [comment]
I am working on Debian 11 for ZynqMP Xilinx's device. And kernel v5.4.0 created by petalinux 2020.2 
I see in cross compile parameter using "4.19.0-xlnx-v2019.1" mean kernel version 4.19 petalinux version is 2019.1 as bellow

shell$ sudo debian/rules ARCH=arm64 DEB_ARCH=arm64 KERNEL_RELEASE=4.19.0-xlnx-v2019.1-zynqmp-fpga KERNEL_SRC_DIR=~/work/ZynqMP-FPGA-Linux/**linux-xlnx-v2019.1-zynqmp-fpga** binary
    :
    
shell$ file ../zynqmp-gpu-4.19.0-xlnx-v2019.1-zynqmp-fpga_0.1.2-0_arm64.deb 
../zynqmp-gpu-4.19.0-xlnx-v2019.1-zynqmp-fpga_0.1.2-0_arm64.deb: Debian binary package (format 2.0)


 So how can I find the build source for Kernel 5.4.0. may be parameter should changed to "KERNEL_RELEASE=5.4.0-xlnx-v2020.2-zynqmp-fpga"

**Comment by ikwzm** [comment]
I'm sorry I couldn't help you. 

I'm not using Petalinux.

**Comment by thangta** [comment]
yes, many thank for your response
